# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UVMUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('netid', models.CharField(max_length=8, unique=True)),
                ('first_name', models.CharField(max_length=40, null=True)),
                ('last_name', models.CharField(max_length=40, null=True)),
                ('uvm_email', models.CharField(max_length=40, null=True)),
                ('full_name', models.CharField(max_length=150, null=True)),
                ('department', models.CharField(max_length=40, null=True)),
                ('facebook_url', models.CharField(max_length=100, null=True)),
                ('additional_email_1', models.CharField(max_length=100, null=True)),
                ('additional_email_2', models.CharField(max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=14, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
