# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventsapp', '0002_auto_20160402_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='latitutde',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='longitube',
            field=models.FloatField(null=True),
        ),
    ]
