# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-02 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventsapp', '0006_auto_20160402_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(default='blah', max_length=255),
            preserve_default=False,
        ),
    ]
